### ISSUE TITLE
Link "save job" button to back-end queries for premium user

### ISSUE THREAD

**Issue by chntlc** [andrewzulaybar/employmee#5]

**Comment by emecke** [comment]
insert statement works but if you click the button twice you get an error bc you're trying to add the same line twice.

**Comment by emecke** [comment]
added delete statement to button on saved-jobs page

**Comment by emecke** [comment]
changed button icon to remove in saved jobs list, edited context for saved jobs so that only jobs saved by the current user are listed. added error checking to ignore errors inserting/deleting to saves_job
